### ISSUE TITLE
Destroy does not remove the ssh association

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-ssh#14]
Running :destroy on a machine resource only deletes the node object. I think it should also delete the .chef/provisioning/ssh/xxxx.json object. That way, it would be possible to then run the create recipe again, with a different IP address and/or machine chef server URL.

**Comment by double-z** [comment]
Hi Christine,

This was actually fixed in the latest release:

https://github.com/chef/chef-provisioning-ssh/blob/master/lib/chef/provisioning/ssh_driver/driver.rb#L90
 
it went out as 0.0.9 yesterday.

**Comment by christinedraper** [comment]
Thanks!
