### ISSUE TITLE
Ideally, destroy would use stored chef_server_url

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-ssh#15]
I have a recipe:

```
with_chef_server node['automateinsights']['provisioning']['chef_server_url']
machine 'myserver' 
```

Ideally, I would like to do the following to destroy it:

```
machine 'myserver' do
  action :destroy
end
```

but I have to specify the chef server in the destroy recipe, or it does not find the machine. Ideally, it would use the chef_server_url which is in the .chef/provisioning/ssh file.

**Comment by double-z** [comment]
good point on this. gonna need to look in to how to make that happen, as that node deletion doesn't happen in the driver per se... probably going to be a matter of overriding or merging the convergence options.

**Comment by christinedraper** [comment]
I guess this may be something that would better be done in chef-provisioning itself, if it makes sense

**Comment by christinedraper** [comment]
Closing this. With hindsight, the less we depend on files in the filesystem, the better.
