### ISSUE TITLE
WinRM :port setting fails validation

### ISSUE THREAD

**Issue by xenolinguist** [chef/chef-provisioning-ssh#25]
Tried using the example for WinRM in the README (edited for correct IP): https://github.com/chef/chef-provisioning-ssh/blame/master/README.md#L110-L118

My chef-client run errored with:
```
    RuntimeError
    ------------
    Machine Options for builder-windows-local are invalid cannot create machine.

    Resource Declaration:
    ---------------------
```

After debugging, I found the culprit is here: https://github.com/chef/chef-provisioning-ssh/blob/master/lib/chef/provisioning/ssh_driver/driver.rb#L222-L223

The `unless extra == :port` causes the validation error message to be suppressed, but the validation still fails (the `valid = false` on the next line).

**Comment by christinedraper** [comment]
Problem still exists, reported on forum https://discourse.chef.io/t/bootstraping-windows-node-using-machine-resource/8490
