### ISSUE TITLE
Consecutive uses of the machine resource fail when omitting machine_options

### ISSUE THREAD

**Issue by Adracus** [chef/chef-provisioning-ssh#29]
When I provision a machine using the following

```ruby
machine 'server' do
  machine_options :transport_options => {
    :ip_address ....
  }
  recipe "my::recipe"
end
```

everything goes fine. But once I omit the `machine_options` in a consecutive call after
the above one like so

```ruby
machine 'server' do
  recipe "another::recipe"
end
```

I get the error

    "Machine Options for server are invalid cannot create machine. :transport_options required"

How can I provision a machine without specifying this everytime? Each other driver fetches the required data from nodes or clients, how about chef-provisioning-ssh?

**Comment by simonseif** [comment]
+1
